/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.geoconverter.view;

/**
 *
 * @author Usuario
 */
public class FRMLocation1 extends javax.swing.JPanel {

    /**
     * Creates new form FRMLocation1
     */
    public FRMLocation1() {
        initComponents();
        cmbProvinces.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbProvinces = new javax.swing.JComboBox<>();
        cmbCantons = new javax.swing.JComboBox<>();
        btnSubit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaLocation = new javax.swing.JTextArea();

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("LOCATION");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("PROVINCES:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("CANTONS:");

        cmbProvinces.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        cmbProvinces.setForeground(new java.awt.Color(102, 0, 204));
        cmbProvinces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AZUAY", "CAÑAR", "EL ORO", "PICHINCHA" }));
        cmbProvinces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvincesActionPerformed(evt);
            }
        });

        cmbCantons.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCantons.setForeground(new java.awt.Color(0, 51, 255));

        btnSubit.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        btnSubit.setForeground(new java.awt.Color(204, 0, 0));
        btnSubit.setText("SUBIT");
        btnSubit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubitActionPerformed(evt);
            }
        });

        txtAreaLocation.setBackground(new java.awt.Color(204, 204, 255));
        txtAreaLocation.setColumns(20);
        txtAreaLocation.setRows(5);
        jScrollPane1.setViewportView(txtAreaLocation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProvinces, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCantons, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnSubit)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbProvinces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCantons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addComponent(btnSubit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProvincesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvincesActionPerformed
        try {
            if (cmbProvinces.getSelectedItem().equals("AZUAY"));
            {
                cmbCantons.removeAllItems();
                cmbCantons.addItem(null);
                cmbCantons.addItem("QUITO");
                cmbCantons.addItem("MACHALA");
                cmbCantons.addItem("ARENILLAS");
                cmbCantons.addItem("RUMIÑAHUI");
                cmbCantons.addItem("AZOGUES");
                cmbCantons.addItem("CAÑAR");
                cmbCantons.addItem("CUENCA");
                cmbCantons.addItem("NABÓN");

            }
            if (cmbProvinces.getSelectedItem().equals("CAÑAR"));
            {
                cmbCantons.removeAllItems();
                cmbCantons.addItem(null);
                cmbCantons.addItem("QUITO");
                cmbCantons.addItem("MACHALA");
                cmbCantons.addItem("ARENILLAS");
                cmbCantons.addItem("RUMIÑAHUI");
                cmbCantons.addItem("AZOGUES");
                cmbCantons.addItem("CAÑAR");
                cmbCantons.addItem("CUENCA");
                cmbCantons.addItem("NABÓN");

            }
            if (cmbProvinces.getSelectedItem().equals("EL ORO"));
            {
                cmbCantons.removeAllItems();
                cmbCantons.addItem(null);
                cmbCantons.addItem("QUITO");
                cmbCantons.addItem("MACHALA");
                cmbCantons.addItem("ARENILLAS");
                cmbCantons.addItem("RUMIÑAHUI");
                cmbCantons.addItem("AZOGUES");
                cmbCantons.addItem("CAÑAR");
                cmbCantons.addItem("CUENCA");
                cmbCantons.addItem("NABÓN");

            }
            if (cmbProvinces.getSelectedItem().equals("PICHINCHA "));
            {
                cmbCantons.removeAllItems();
                cmbCantons.addItem(null);
                cmbCantons.addItem("QUITO");
                cmbCantons.addItem("MACHALA");
                cmbCantons.addItem("ARENILLAS");
                cmbCantons.addItem("RUMIÑAHUI");
                cmbCantons.addItem("AZOGUES");
                cmbCantons.addItem("CAÑAR");
                cmbCantons.addItem("CUENCA");
                cmbCantons.addItem("NABÓN");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cmbProvincesActionPerformed

    private void btnSubitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubitActionPerformed

        String Provinces = (String) cmbProvinces.getSelectedItem();
        cmbProvinces.setSelectedItem(null);
        cmbCantons.setSelectedItem(null);
        String Cantons = (String) cmbCantons.getSelectedItem();
        txtAreaLocation.append("\n Selected Pronvinces is :" + Provinces + "\n Selected Cantons is :" + Cantons + "\n");

    }//GEN-LAST:event_btnSubitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubit;
    private javax.swing.JComboBox<String> cmbCantons;
    private javax.swing.JComboBox<String> cmbProvinces;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaLocation;
    // End of variables declaration//GEN-END:variables
}
